#!/bin/env bash

# Wrapper for `ack` that skips common virtual environment and tox directories,
# and uses `less -R` as the pager to preserve ANSI colors in the output.

ack --ignore-dir=.venvs --ignore-dir=.venv --ignore-dir=.tox --pager="less -R" "$@"
