#!/bin/sh

# The script "monitors" configures monitors correctly
# by detecting which are present.
# This is of limited use.
# Two screens
# Two external monitors ON
# Laptop screen OFF

xrandr --output DisplayPort-1 --auto --left-of HDMI-A-0 \
       --output HDMI-A-0 --auto --primary \
       --output eDP --off
