#!/bin/sh

# Run rlwrap to provide readline support for Mathematica.
# The -rawterm option disables any readline-like features in `math` itself,
# which would otherwise interfere badly with rlwrap's readline.

# -p'0;32'    Use green color for the input prompt, or
# -p'green'   Use green color for the input prompt.

# -r          Enable history support; the history file will be named ~/.mmath_history
#             (since this script is named `mmath`).

# -z handle_hotkeys
#             Enables a few select key bindings in ~/.inputrc (see below for details).

# -f ~/bin/mma_words
#             Use a list of words for completion, taken from the list of built-in symbols
#             in an Emacs package.

rlwrap -p'green' -r -z handle_hotkeys -f ~/bin/mma_words /usr/local/bin/math -rawterm

########################
# ---- ~/.inputrc ----
# Use fzf to search history in rlwrap
# "\C-f": rlwrap-hotkey

# Since the binding above clobbers Ctrl-F, bind another key to forward-char
# "\C-g": forward-char
# ---------------------
